package org.test.services.demoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2017-10-23T14:11:57.561+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://test.org/services/DemoService/", name = "DemoService")
@XmlSeeAlso({org.test.entities.demo.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DemoService {

    @WebMethod
    @WebResult(name = "EchoResponseType", targetNamespace = "http://test.org/entities/Demo", partName = "parameters")
    public org.test.entities.demo.EchoResponseType echo(
        @WebParam(partName = "parameters", name = "EchoRequestType", targetNamespace = "http://test.org/entities/Demo")
        org.test.entities.demo.EchoRequestType parameters
    );
}
